# Site settings
title: maxell's site
email: 0087yugbocaj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site that some dumb kid made.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maxell.ml" # the base hostname & protocol for your site
github_username:  maxellnormalbias

# Build settings
markdown: kramdown

#motd
motd: "Well, summer's finally here. I can actually work on this website now."
