# Site settings
title: maxell's site
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  qwertyuiopasdfghjklzxcvbnm
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maxellnormalbias.github.io" # the base hostname & protocol for your site
github_username:  maxellnormalbias

# Build settings
markdown: kramdown
